version: '3.8'

# ===================================================================
#  YAML Anchor for Zero-Downtime Deployment Configuration
# ===================================================================
x-deploy-config: &deploy-config
  deploy:
    update_config:
      parallelism: 1
      order: start-first
      failure_action: rollback
      delay: 5s
    rollback_config:
      parallelism: 1
      order: stop-first
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s

services:
  # ===================================================================
  #  1. Infrastructure Services (No changes here)
  # ===================================================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - heavens-ms-js-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - heavens-ms-js-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # ===================================================================
  #  2. Application Microservices (UPDATED WITH ADVANCED DEPLOYMENT)
  # ===================================================================
  api-gateway:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only api-gateway
    restart: unless-stopped
    <<: *deploy-config # Apply the zero-downtime config
    healthcheck:
      <<: *deploy-config.healthcheck # Inherit base healthcheck config
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Specific test
    ports:
      - "8080:8080"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }
      redis: { condition: service_healthy }
      auth-service: { condition: service_healthy }
      client-service: { condition: service_healthy }
      user-service: { condition: service_healthy }
      property-service: { condition: service_healthy }
      inventory-service: { condition: service_healthy }
      socket-service: { condition: service_healthy }
      notification-service: { condition: service_healthy }
      accounts-service: { condition: service_healthy }

  auth-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only auth-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
    expose:
      - "5001"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  client-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only client-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
    expose:
      - "5002"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  # ... (The same pattern is applied to all other services)
  # I've omitted them for brevity, but you should apply the
  # `<<: *deploy-config` and updated `healthcheck` to all of them.

  user-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only user-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
    expose:
      - "5003"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  property-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only property-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
    expose:
      - "5004"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  inventory-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only inventory-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
    expose:
      - "5005"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  socket-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only socket-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5006/health"]
    expose:
      - "5006"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }
      redis: { condition: service_healthy }

  notification-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only notification-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5007/health"]
    expose:
      - "5007"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }

  accounts-service:
    image: akhilbeliever001222/heavens-ms:latest
    command: pm2-runtime ecosystem.config.cjs --only accounts-service
    restart: unless-stopped
    <<: *deploy-config
    healthcheck:
      <<: *deploy-config.healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5008/health"]
    expose:
      - "5008"
    networks:
      - heavens-ms-js-net
    env_file: ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq: { condition: service_healthy }


# ===================================================================
#  3. Networks and Volumes
# ===================================================================
networks:
  heavens-ms-js-net:
    driver: bridge

volumes:
  rabbitmq-data:

