// ⭐️ --- START UPDATE ---
// This file REPLACES accountMapping.config.js
// It defines permanent system keys that admins will map to accounts in the UI.

/**
 * Defines standard, permanent system names used for automated journal entries.
 * These keys are used by the AccountSetting service to find the correct,
 * dynamically-mapped account (ledger) ID for a transaction.
 */
export const ACCOUNT_SYSTEM_NAMES = {
  // ----- ASSETS -----
  ASSET_CORE_BANK: "ASSET_CORE_BANK", // Main bank account for online/UPI transactions
  ASSET_CORE_CASH: "ASSET_CORE_CASH", // Main cash-in-hand account
  ASSET_PETTY_CASH: "ASSET_PETTY_CASH",
  ASSET_ACCOUNTS_RECEIVABLE: "ASSET_ACCOUNTS_RECEIVABLE", // For bill-wise tracking
  ASSET_INVENTORY: "ASSET_INVENTORY",
  // ASSET_FURNITURE_FIXTURES: "ASSET_FURNITURE_FIXTURES",
  ASSET_NON_CURRENT: "ASSET_NON_CURRENT",
  ASSET_SALARY_ADVANCES: "ASSET_SALARY_ADVANCES",

  // ----- LIABILITIES -----
  LIABILITY_SECURITY_DEPOSIT: "LIABILITY_SECURITY_DEPOSIT",
  LIABILITY_ACCOUNTS_PAYABLE: "LIABILITY_ACCOUNTS_PAYABLE", // For bill-wise tracking
  LIABILITY_SALARIES_PAYABLE: "LIABILITY_SALARIES_PAYABLE",
  LIABILITY_BUS_FEE_PAYABLE: "LIABILITY_BUS_FEE_PAYABLE",

  // ----- GST LIABILITIES (OUTPUT TAX) -----
  LIABILITY_GST_OUTPUT_CGST_2_5: "LIABILITY_GST_OUTPUT_CGST_2_5", // For 5% slab
  LIABILITY_GST_OUTPUT_SGST_2_5: "LIABILITY_GST_OUTPUT_SGST_2_5", // For 5% slab
  LIABILITY_GST_OUTPUT_IGST_5: "LIABILITY_GST_OUTPUT_IGST_5", // For 5% slab

  LIABILITY_GST_OUTPUT_CGST_6: "LIABILITY_GST_OUTPUT_CGST_6", // For 12% slab
  LIABILITY_GST_OUTPUT_SGST_6: "LIABILITY_GST_OUTPUT_SGST_6", // For 12% slab
  LIABILITY_GST_OUTPUT_IGST_12: "LIABILITY_GST_OUTPUT_IGST_12", // For 12% slab

  LIABILITY_GST_OUTPUT_CGST_9: "LIABILITY_GST_OUTPUT_CGST_9", // For 18% slab
  LIABILITY_GST_OUTPUT_SGST_9: "LIABILITY_GST_OUTPUT_SGST_9", // For 18% slab
  LIABILITY_GST_OUTPUT_IGST_18: "LIABILITY_GST_OUTPUT_IGST_18", // For 18% slab

  LIABILITY_GST_OUTPUT_CGST_14: "LIABILITY_GST_OUTPUT_CGST_14", // For 28% slab
  LIABILITY_GST_OUTPUT_SGST_14: "LIABILITY_GST_OUTPUT_SGST_14", // For 28% slab
  LIABILITY_GST_OUTPUT_IGST_28: "LIABILITY_GST_OUTPUT_IGST_28", // For 28% slab

  // ----- GST ASSETS (INPUT TAX CREDIT) -----
  ASSET_GST_INPUT_CGST_2_5: "ASSET_GST_INPUT_CGST_2_5",
  ASSET_GST_INPUT_SGST_2_5: "ASSET_GST_INPUT_SGST_2_5",
  ASSET_GST_INPUT_IGST_5: "ASSET_GST_INPUT_IGST_5",

  ASSET_GST_INPUT_CGST_6: "ASSET_GST_INPUT_CGST_6",
  ASSET_GST_INPUT_SGST_6: "ASSET_GST_INPUT_SGST_6",
  ASSET_GST_INPUT_IGST_12: "ASSET_GST_INPUT_IGST_12",

  ASSET_GST_INPUT_CGST_9: "ASSET_GST_INPUT_CGST_9",
  ASSET_GST_INPUT_SGST_9: "ASSET_GST_INPUT_SGST_9",
  ASSET_GST_INPUT_IGST_18: "ASSET_GST_INPUT_IGST_18",

  ASSET_GST_INPUT_CGST_14: "ASSET_GST_INPUT_CGST_14",
  ASSET_GST_INPUT_SGST_14: "ASSET_GST_INPUT_SGST_14",
  ASSET_GST_INPUT_IGST_28: "ASSET_GST_INPUT_IGST_28",

  // ----- INCOME -----
  INCOME_RENT_MONTHLY: "INCOME_RENT_MONTHLY",
  INCOME_RENT_DAILY: "INCOME_RENT_DAILY",
  INCOME_RENT_MESS: "INCOME_RENT_MESS",
  INCOME_DEPOSIT_NON_REFUNDABLE: "INCOME_DEPOSIT_NON_REFUNDABLE",
  INCOME_MISCELLANEOUS: "INCOME_MISCELLANEOUS",
  INCOME_SALES: "INCOME_SALES", // Generic sales account

  // ----- EXPENSES -----
  EXPENSE_SALARIES: "EXPENSE_SALARIES",
  EXPENSE_COMMISSION: "EXPENSE_COMMISSION",
  EXPENSE_MAINTENANCE: "EXPENSE_MAINTENANCE",
  EXPENSE_GENERAL: "EXPENSE_GENERAL", // A fallback
  EXPENSE_MESS_SUPPLIES: "EXPENSE_MESS_SUPPLIES",
  EXPENSE_UTILITIES: "EXPENSE_UTILITIES",

  // ----- EQUITY -----
  EQUITY_RETAINED_EARNINGS: "EQUITY_RETAINED_EARNINGS", // For P&L calculation
};
// ⭐️ --- END UPDATE ---
