export const PROPERTY_PATTERN = {
  PROPERTY: {
    CREATE_PROPERTY: "create_property",
    UPDATE_PROPERTY: "update_property",
    DELETE_PROPERTY: "delete_property",
    GET_PROPERTY_BY_ID: "get_property_by_id",
    GET_ALL_HEAVENS_PROPERTIES: "get_all_heavens_property",
    GET_CLIENT_PROPERTIES: "get_client_properties",
  },
  ROOM: {
    CREATE_ROOM: "create_room",
    UPDATE_ROOM: "update_room",
    DELETE_ROOM: "delete_room",
    GET_ROOMS_BY_PROPERTYID: "get_rooms_by_propertyId",
    GET_ROOM_OCCUPANTS: "get_room_occupants",
    GET_AVAILABLE_ROOMS_BY_PROPERTY: "get_available_rooms_by_property",
    GET_ALL_HEAVENS_ROOMS: "get_all_heavens_rooms",
    CONFIRM_ASSIGNMENT: "confirm_assignment",
    REMOVE_ASSIGNMENT: "remove_assignment",
  },
  STAFF: {
    GET_ALL_STAFF: "get_all_staff",
    GET_STAFF_BY_ID: "get_staff_by_id",
    DELETE_STAFF: "delete_staff",
    STAFF_STATUS_CHANGE: "staff_status_change",
    GET_STAFF_BY_PROPERTYID: "get_staff_by_propertyId",
    ADD_STAFF: "add_staff",
    UPDATE_STAFF: "update_staff",
  },
  PROPERTY_LOG: {
    GET_ACTIVITY_LOG: "get_activity_log",
  },
  INTERNAL: {
    UPDATE_PROPERTY_COUNTS: "update_property_counts",
  },
  MAINTENANCE: {
    CREATE: "property_maintenance_create",
    GET_BY_PROPERTY: "property_maintenance_get_by_property",
    ASSIGN_STAFF: "property_maintenance_assign_staff",
    MARK_RESOLVED: "property_maintenance_mark_resolved",
    GET_BY_ID: "property_maintenance_get_by_id",
    GET_BY_USER: "property_maintenance_get_by_user",
    GET_ALL: "property_maintenance_get_all",
    UPDATE: "property_maintenance_update",
    DELETE: "property_maintenance_delete",
  },
  DASHBOARD: {
    GET_DASHBOARD_DATA: "get_dashbaord_data",
    GET_STAFF_COUNTS: "get_staff_counts",
    GET_MAINTENANCE_COUNTS: "get_maintenance_counts",
    GET_OCCUPANCY_RATE: "get_ocuupancy_rate",
  },
  ATTENDANCE: {
    MARK_ATTENDANCE: "mark_attendance",
    GET_ATTENDANCE: "get_attendance",
    UPDATE_ATTENDANCE: "update_attendance",
  },
  CAROUSEL: {
    ADD_CAROUSEL: "add_carousel",
    UPDATE_CAROUSEL: "update_carousel",
    DELETE_CAROUSEL: "delete_carousel",
    GET_ALL_CAROUSEL: "get_all_carousel",
  },
};
