export const USER_PATTERN = {
  USER: {
    GET_USER_BY_EMAIL: "get_user_by_email",
    REGISTER_USER: "register_user",
    UNAPPROVED_USER: "unapproved_user",
    APPROVE_USER: "approve_user",
    REJECT_USER: "reject_user",
    VERIFY_EMAIL: "verify_email",
    UPDATE_PROFILE: "update_profile",
    ADMIN_UPDATE_PROFILE: "admin_update_profile",
    GET_USER_BY_ID: "get_user_by_id",
    GET_USERS_BY_RENT_TYPE: "get_users_by_rent_type",
    GET_CHECKOUTED_USERS_BY_RENT_TYPE: "get_checkouted_users_by_rent_type",
    VACATE_USER: "vacate_user",
    REJOIN_USER: "rejoin_user",
    GET_USER_IDS: "get_user_ids",
    GET_USERS_FOR_NOTIFICATION: "get_users_for_notification",
    GET_TODAY_CHECKOUTS: "get_today_checkouts",
    EXTEND_USER_DAYS: "extend_user_days",
    CREATE_STATUS_REQUEST: "create_status_request",
    GET_PENDING_STATUS_REQUESTS: "get_pending_stutus_requests",
    RESPOND_TO_STATUS_REQUEST: "respond_to_status_request",
    GET_USER_STATUS_REQUESTS: "get_user_status_requests",
    HANDLE_BLOCK_STATUS: "handle_block_status",
    FETCH_USER_DATA: "fetch_user_data",
    
  },
  PASSWORD: {
    SET_RESET_TOKEN: "set_reset_token",
    GET_USER_BY_RESET_TOKEN: "get_user_by_reset_token",
    UPDATE_PASSWORD: "update_password",
  },
};
