export const USER_PATTERN = {
  USER: {
    GET_USER_BY_EMAIL: "get_user_by_email",
    REGISTER_USER: "register_user",
    UNAPPROVED_USER: "unapproved_user",
    APPROVE_USER: "approve_user",
    REJECT_USER: "reject_user",
    VERIFY_EMAIL: "verify_email",
    UPDATE_PROFILE: "update_profile",
    UPDATE_USER: "update_user",
    ADMIN_UPDATE_PROFILE: "admin_update_profile",
    GET_USER_BY_ID: "get_user_by_id",
    GET_USERS_BY_RENT_TYPE: "get_users_by_rent_type",
    GET_CHECKOUTED_USERS_BY_RENT_TYPE: "get_checkouted_users_by_rent_type",
    VACATE_USER: "vacate_user",
    REJOIN_USER: "rejoin_user",
    GET_USER_IDS: "get_user_ids",
    GET_USERS_FOR_NOTIFICATION: "get_users_for_notification",
    GET_TODAY_CHECKOUTS: "get_today_checkouts",
    EXTEND_USER_DAYS: "extend_user_days",
    CREATE_STATUS_REQUEST: "create_status_request",
    GET_PENDING_STATUS_REQUESTS: "get_pending_stutus_requests",
    RESPOND_TO_STATUS_REQUEST: "respond_to_status_request",
    GET_USER_STATUS_REQUESTS: "get_user_status_requests",
    HANDLE_BLOCK_STATUS: "handle_block_status",
    FETCH_USER_DATA: "fetch_user_data",
    GET_USERS_WITH_BIRTHDAY_TODAY: "get_users_with_birthday_today",
    GET_USER_BY_AGENCY: "get_user_by_agency"
  },
  PASSWORD: {
    SET_RESET_TOKEN: "set_reset_token",
    GET_USER_BY_RESET_TOKEN: "get_user_by_reset_token",
    UPDATE_PASSWORD: "update_password",
  },
  LOG: {
    GET_ACTIVITY_LOGS: "get_activity_logs",
  },
  REMINDER_NOTE: {
    CREATE_NOTE: "create_note",
    GET_USER_NOTES: "get_user_notes",
    GET_ACTIVE_REMINDERS: "get_active_reminders",
    UPDATE_NOTE: "update_note",
    COMPLETE_REMINDER: "complete_reminder",
    SNOOZE_REMINDER: "snooze_reminder",
    DELETE_NOTE: "delete_note",
  },
  PAYMENT: {
    GET_ALL_PAYMENT_PENDING_USERS: "get_all_payment_pending_users",
  },
  DASHBOARD: {
    GET_USERS_COUNTS: "get_users_counts",
    GET_USER_STATISTICS_FOR_ACCOUNTS_DASHBOARD:
      "get_user_statistics_for_accounts_dashboard",
  },
  REFERRAL: {
    GET_USER_REFERRAL_DETAILS: "user_referral_get_details",
    COMPLETE_REFERRAL: "user_referral_complete",
    GET_SETTINGS: "get_referral_settings",
    UPDATE_SETTINGS: "update_referral_settings",
  },
};
