export const PERMISSIONS = {
  // ----- ACCOUNTS -----
  ACCOUNTS_VIEW: "ACCOUNTS_VIEW",
  ACCOUNTS_MANAGE: "ACCOUNTS_MANAGE",
  ACCOUNTS_DASHBOARD_VIEW: "ACCOUNTS_DASHBOARD_VIEW",
  COMMISSION_VIEW: "COMMISSION_VIEW",
  COMMISSION_MANAGE: "COMMISSION_MANAGE",
  DEPOSIT_VIEW: "DEPOSIT_VIEW",
  DEPOSIT_MANAGE: "DEPOSIT_MANAGE",
  EXPENSE_VIEW: "EXPENSE_VIEW",
  EXPENSE_MANAGE: "EXPENSE_MANAGE",
  FEE_PAYMENT_VIEW: "FEE_PAYMENT_VIEW",
  FEE_PAYMENT_MANAGE: "FEE_PAYMENT_MANAGE",
  SALARY_VIEW: "SALARY_VIEW",
  SALARY_MANAGE: "SALARY_MANAGE",
  VOUCHER_VIEW: "VOUCHER_VIEW",
  VOUCHER_MANAGE: "VOUCHER_MANAGE",
  LOGS_ACCOUNTS_VIEW: "LOGS_ACCOUNTS_VIEW",

  // ----- AUTH -----
  ROLES_VIEW: "ROLES_VIEW",
  ROLES_MANAGE: "ROLES_MANAGE",

  // ----- CLIENT -----
  CLIENT_MANAGE: "CLIENT_MANAGE",
  AGENCY_VIEW: "AGENCY_VIEW",
  AGENCY_MANAGE: "AGENCY_MANAGE",
  MANAGER_VIEW: "MANAGER_VIEW",
  MANAGER_MANAGE: "MANAGER_MANAGE",
  PETTY_CASH_VIEW: "PETTY_CASH_VIEW",
  PETTY_CASH_MANAGE: "PETTY_CASH_MANAGE",

  // ----- INVENTORY -----
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",
  ADDON_VIEW: "ADDON_VIEW",
  ADDON_MANAGE: "ADDON_MANAGE",
  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_MANAGE: "CATEGORY_MANAGE",
  KITCHEN_VIEW: "KITCHEN_VIEW",
  KITCHEN_MANAGE: "KITCHEN_MANAGE",
  MENU_VIEW: "MENU_VIEW",
  MENU_MANAGE: "MENU_MANAGE",
  BOOKING_VIEW: "BOOKING_VIEW",
  BOOKING_MANAGE: "BOOKING_MANAGE",
  LOGS_INVENTORY_VIEW: "LOGS_INVENTORY_VIEW",

  // ----- NOTIFICATION -----
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",
  NOTIFICATION_MANAGE: "NOTIFICATION_MANAGE",

  // ----- PROPERTY -----
  PROPERTY_VIEW: "PROPERTY_VIEW",
  PROPERTY_MANAGE: "PROPERTY_MANAGE",
  ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
  ATTENDANCE_MANAGE: "ATTENDANCE_MANAGE",
  CAROUSEL_VIEW: "CAROUSEL_VIEW",
  CAROUSEL_MANAGE: "CAROUSEL_MANAGE",
  MAINTENANCE_VIEW: "MAINTENANCE_VIEW",
  MAINTENANCE_MANAGE: "MAINTENANCE_MANAGE",
  ROOM_VIEW: "ROOM_VIEW",
  ROOM_MANAGE: "ROOM_MANAGE",
  STAFF_VIEW: "STAFF_VIEW",
  STAFF_MANAGE: "STAFF_MANAGE",
  LOGS_PROPERTY_VIEW: "LOGS_PROPERTY_VIEW",
  PROPERTY_DASHBOARD_VIEW: "PROPERTY_DASHBOARD_VIEW",

  // ----- USER -----
  USER_VIEW: "USER_VIEW",
  USER_MANAGE: "USER_MANAGE",
  USER_APPROVAL: "USER_APPROVAL",
  USER_STATUS_MANAGE: "USER_STATUS_MANAGE",
  REFERRAL_VIEW: "REFERRAL_VIEW",
  REFERRAL_MANAGE: "REFERRAL_MANAGE",
  REMINDER_VIEW: "REMINDER_VIEW",
  REMINDER_MANAGE: "REMINDER_MANAGE",
  LOGS_USER_VIEW: "LOGS_USER_VIEW",

  // ----- SYSTEM -----
  SOCKET_MANAGE: "SOCKET_MANAGE",
  ALL_PRIVILEGES: "ALL_PRIVILEGES", // Grants access to everything
};
