export const ACCOUNTS_PATTERN = {
  FEE_PAYMENTS: {
    ADD_FEE_PAYMENTS: "add_fee_payments",
    UPDATE_FEE_PAYMENT: "update_fee_payments",
    GET_FEE_PAYMENT: "get_fee_payment",
    INITIATE_ONLINE: "payment_initiate_online",
    VERIFY_ONLINE: "payment_verify_online",
    RECORD_MANUAL: "payment_record_manual",
    GET_ALL_FEE_PAYMENTS: "get_all_fee_payments",
    GET_MONTHWISE_TOTAL_COLLECTION: "get_monthwise_total_collection",
    GET_ALL_PENDING_PAYMENTS: "get_all_pending_payments",
    GET_LATEST_BY_USERS: "get_latest_by_users",
    GET_FINANCIAL_SUMMARY: "get_Financial_Summary",
    GET_NEXT_DUE_DATE: "get_next_due_date",
    GET_PAYMENT_SUMMARY: "get_payment_summary",
  },
  COMMISSION: {
    ADD_COMMISSION: "add_commission",
    GET_COMMISSION_BY_ID: "get_commission_by_id",
    GET_ALL_COMMISSION: "get_all_commission",
    EDIT_COMMISSION: "edit_commission",
    DELETE_COMMISSION: "delete_commission",
    GET_ALL_COMMISSION_BY_USER: "get_all_commission_by_user",
  },
  EXPENSE: {
    ADD_EXPENSE : "add_expense",
    GET_ALL_EXPENSES: "get_all_expense",
    GET_EXPENSE_BY_ID: "get_expense_by_id",
    DELETE_EXPENSE: "delete_expense",
    ADD_EXPENSE_CATEGORY: "add_expense_category",
    GET_CATEGORY_BY_MAINCATEROGY: "get_category_by_main_category",
    GET_ALL_CATEGORIES: "get_all_categories",
    DELETE_CATEGORY: "delete_category",
  },
};
