export const ACCOUNTS_PATTERN = {
  FEE_PAYMENTS: {
    ADD_FEE_PAYMENTS: "add_fee_payments",
    UPDATE_FEE_PAYMENT: "update_fee_payments",
    GET_FEE_PAYMENT: "get_fee_payment",
    INITIATE_ONLINE: "payment_initiate_online",
    VERIFY_ONLINE: "payment_verify_online",
    RECORD_MANUAL: "payment_record_manual",
    GET_ALL_FEE_PAYMENTS: "get_all_fee_payments",
    GET_MONTHWISE_TOTAL_COLLECTION: "get_monthwise_total_collection",
    GET_ALL_PENDING_PAYMENTS: "get_all_pending_payments",
    GET_LATEST_BY_USERS: "get_latest_by_users",
    GET_FINANCIAL_SUMMARY: "get_Financial_Summary",
    GET_NEXT_DUE_DATE: "get_next_due_date",
    GET_PAYMENT_SUMMARY: "get_payment_summary",
    GET_PAYMENTS_BY_USERID: "get_payments_by_userId",
    GET_WAVEOFF_PAYMENTS: "get_waveoff_payments",
    GET_ALL_CASH_PAYMENTS: "get_all_cash_payments",
    GET_LATEST_PAYMENT_BY_USERID: "get_latest_payment_by_userId",
    GET_FEE_PAYMENTS_ANALYTICS: "get_fee_payment_analytics",
    GET_TRANSACTIONS_BY_USERID: "get_transactions_by_userId",
  },
  DEPOSIT_PAYMENTS: {
    INITIATE_ONLINE_DEPOSIT: "deposit_payment_initiate_online",
    VERIFY_ONLINE_DEPOSIT: "deposit_payment_verify_online",
    RECORD_MANUAL_DEPOSIT: "deposit_payment_record_manual",
    GET_ALL_DEPOSIT_PAYMENTS: "get_all_deposit_payments",
    GET_LATEST_DEPOSIT_PAYMENT_BY_USERID:
      "get_latest_deposit_payment_by_userId",
    RECORD_REFUND_PAYMENT: "record_refund_payment",
    GET_TRANSACTIONS_BY_USERID: "get_dep_transactions_by_userid",
  },
  BUS_PAYMENTS: {
    INITIATE_ONLINE_BUS_PAYMENT: "bus_payment_initiate_online",
    VERIFY_ONLINE_BUS_PAYMENT: "bus_payment_verify_online",
    RECORD_MANUAL_BUS_PAYMENT: "bus_payment_record_manual",
    GET_ALL_BUS_PAYMENTS: "get_all_bus_payments",
    GET_LATEST_BUS_PAYMENT_BY_USERID: "get_latest_bus_payment_by_userId",
    RECORD_REFUND_PAYMENT: "record_refund_payment",
    GET_TRANSACTIONS_BY_USERID: "get_bus_transactions_by_userid",
  },
  COMMISSION: {
    ADD_COMMISSION: "add_commission",
    GET_COMMISSION_BY_ID: "get_commission_by_id",
    GET_ALL_COMMISSION: "get_all_commission",
    EDIT_COMMISSION: "edit_commission",
    DELETE_COMMISSION: "delete_commission",
    GET_ALL_COMMISSION_BY_USER: "get_all_commission_by_user",
    GET_COMMISSION_BY_PROPERTY: "get_commission_by_property",
  },
  DASHBOARD: {
    GET_ACCOUNT_DASHBAORD_DATA_FOR_INCOME_SECTION:
      "get_account_dashbaord_data_for_income_section",
    GET_ACCOUNT_DASHBAORD_DATA_FOR_EXPENESE_SECTION:
      "get_account_dashbaord_data_for_expense_section",
    GET_ACCOUNT_DASHBAORD_DATA_FOR_DEPOSIT_SECTION:
      "get_account_dashbaord_data_for_deposit_section",
    GET_MAIN_DASHBAORD_DATA_FOR_INCOME_AND_EXPENSE_SECTION:
      "get_main_dashbaord_data_for_income_and_expense_section",
    GET_GST_REPORT: "get_gst_report",
  },
  EXPENSE: {
    ADD_EXPENSE: "add_expense",
    GET_ALL_EXPENSES: "get_all_expense",
    GET_EXPENSE_BY_ID: "get_expense_by_id",
    DELETE_EXPENSE: "delete_expense",
    ADD_EXPENSE_CATEGORY: "add_expense_category",
    GET_CATEGORY_BY_MAINCATEROGY: "get_category_by_main_category",
    GET_ALL_CATEGORIES: "get_all_categories",
    DELETE_CATEGORY: "delete_category",
    GET_EXPENSE_ANALYTICS: "get_expense_analytics",
    GET_PETTYCASH_PAYMENTS_BY_MANAGER: "get_pettyCash_payments_by_manager",
    UPDATE_EXPENSE: "update_expense",
  },
  VOUCHER: {
    ADD_VOUCHER: "add_voucher",
    DELETE_VOUCHER: "delete_voucher",
    GET_VOUCHER_BY_PROPERTY: "get_voucher_by_property",
  },
  SALARY: {
    MANUAL_CREATE: "manual_add_salary",
    GET_ALL: "get_all_salary_records",
    DELETE_VOUCHER: "delete_voucher",
    GET_VOUCHER_BY_PROPERTY: "get_voucher_by_property",
    UPDATE_STATUS: "update_status",
  },
  LOG: {
    GET_ACCOUNT_LOGS: "get_account_logs",
  },
  ACCOUNTING: {
    CREATE_JOURNAL_ENTRY: "accounting_create_journal_entry",
    CREATE_MANUAL_JOURNAL_ENTRY: "accounting_create_manual_journal_entry",
    GET_JOURNAL_ENTRIES: "get_journal_entries",
    GET_JOURNAL_ENTRY_ID: "get_journal_entry_id",
    VOUCHER_PAYMENT: "accounting_voucher_payment_create",
    VOUCHER_RECEIPT: "accounting_voucher_receipt_create",
    VOUCHER_CONTRA: "accounting_voucher_contra_create",
  },
  REPORT: {
    GET_PNL: "report_get_pnl",
    GET_BALANCE_SHEET: "report_get_balance_sheet",
    GET_DAY_BOOK: "report_get_day_book",
    GET_LEDGER_REPORT: "report_get_ledger_report",
    GET_GSTR1_REPORT: "report_get_gstr1",
  },
  RECONCILIATION: {
    GET_UNRECONCILED: "reconciliation_get_unreconciled",
    RECONCILE_ENTRIES: "reconciliation_reconcile_entries",
  },
  // NEW BILL-WISE PATTERNS
  BILL_LEDGER: {
    GET_OUTSTANDING_BILLS: "bill_ledger_get_outstanding",
    GET_BILL_DETAILS: "bill_ledger_get_details",
  },
  CHART_OF_ACCOUNTS: {
    CATEGORY_CREATE: "coa_category_create",
    CATEGORY_GET_ALL: "coa_category_get_all",
    CATEGORY_UPDATE: "coa_category_update",
    CATEGORY_DELETE: "coa_category_delete",
    ACCOUNT_CREATE: "coa_account_create",
    ACCOUNT_GET_ALL: "coa_account_get_all",
    ACCOUNT_GET_BY_ID: "coa_account_get_by_id",
    ACCOUNT_UPDATE: "coa_account_update",
    ACCOUNT_DELETE: "coa_account_delete",
  },
  ACCOUNT_SETTING: {
    SET_MAPPING: "account_setting_set_mapping",
    GET_MAPPINGS: "account_setting_get_mappings",
    GET_SYSTEM_NAMES: "account_setting_get_system_names",
    CLEAR_CACHE: "account_setting_clear_cache",
  },
};
